_BASE_: "../Base_OVCOCO_C4_1x.yaml"
MODEL:
  ROI_BOX_HEAD:
    CLIP:
      USE_IMAGE_ENCODER: True

CONTEXT_SAMPLING:
  ENABLE: True
  SINGLE_SAMPLING: False
  MULTI_GPU_SYNC: True
  CONTRAST_LOSS_WEIGHT: 0.1
  OBJECTNESS_THR: 0.83
  IN_NMS_IOU_THR: 0.3
  GRACLUS_STEPS: 1
  GRAB_IOF_THR: 0.75
  MAX_GRAB: 1
  SCORE_SIGMOID: True
  OUT_NMS_IOU_THR: 0.3
  MATCH_OUTSKIRT_THR: [0.375, 0.5, 0.6]
