_BASE_: "../Base_OVCOCO_C4_1x.yaml"
MODEL:
  ROI_BOX_HEAD:
    CLIP:
      USE_IMAGE_ENCODER: True

CONTEXT_SAMPLING:
  ENABLE: True
  SINGLE_SAMPLING: True
  MULTI_GPU_SYNC: True
  MASK_SAME_CLASS: True
  CONTRAST_LOSS_WEIGHT: 0.1
  OBJECTNESS_THR: 0.85
  IN_NMS_IOU_THR: 0.3
  MATCH_GIOU_THR: -0.1
  GRACLUS_STEPS: 1
  GRAB_IOF_THR: 0.7
  MAX_GRAB: 1
  SCORE_SIGMOID: True

  NEG_POS_IOU_THR: 0.2
  SINGLE_MAX_POS: 10
  SINGLE_MAX_NEG: 10
  OUT_NMS_IOU_THR: 0.3
SOLVER:
  IMS_PER_BATCH: 8