_BASE_: "../Base_OVCOCO_C4_1x.yaml"
MODEL:
  ROI_BOX_HEAD:
    USE_BIAS: -30.0
    CLIP:
      USE_IMAGE_ENCODER: True

CONTEXT_SAMPLING:
  ENABLE: True
  SINGLE_SAMPLING: False
  MULTI_GPU_SYNC: True
  CONTRAST_LOSS_WEIGHT: 1.0
  OBJECTNESS_THR: 0.80
  IN_NMS_IOU_THR: 0.50
  MATCH_IOS_THR: 0.80
  MATCH_GIOU_THR: -0.10
  MATCH_AREA_RATIO_THR: 0.33
  SINGLE_OBJECTNESS_THR: 0.95
  GRACLUS_STEPS: 1
  GRAB_IOF_THR: 0.75
  MAX_GRAB: 1
  SCORE_SIGMOID: True
  OUT_NMS_IOU_THR: 0.3
  AREA_THR: 2500
