_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "models/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 1203
    SCORE_THRESH_TEST: 0.0001
  ROI_BOX_HEAD:
    NORM_TEMP: 100.0
    MASK_VALUE: -10000000000000000000000.0
    LEARN_BG: True
    BG_BIAS: False
    USE_BIAS: 0.0
    MASK_FOR_NEG: False
    DROP_LAST: False
    ALL_ENCODER: True
    CLS_AGNOSTIC_BBOX_REG: True
    USE_ZEROSHOT_CLS: True
    USE_SIGMOID_CE: False
    USE_FED_LOSS: False
    IGNORE_ZERO_CATS: True
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/lvis_v1_clip_prompt_name.npy'
    CAT_FREQ_PATH: 'datasets/metadata/lvis_v1_train_cat_norare_info.json'
    NUM_WORDS: 4
    WORD_EMBED_DIM: 512
    CLS_LOSS_WEIGHT: 1.0
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
    CLS_AGNOSTIC_MASK: True
DATASETS:
  TRAIN: ("lvis_v1_train_norare",)
  TEST: ("lvis_v1_val",)
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
TEST:
  EVAL_PERIOD: 30000
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  WEIGHT_DECAY: 0.000025
  CHECKPOINT_PERIOD: 210000
  WARMUP_FACTOR: 0.0002
  WARMUP_ITERS: 5000
  CLIP_GRADIENTS:
    ENABLED: True
SEED: 32522135
OUTPUT_DIR: "./output/Detic-lvis-scalability/auto"