_BASE_: "./res101_fpn_3x_clip_kd.yaml"
SOLVER:
  CHECKPOINT_PERIOD: 210000
INPUT:
  CUSTOM_AUG: EfficientDetResizeCrop
  TRAIN_SIZE: 1024
  SCALE_RANGE: (0.5, 2.0)
CONTEXT_MODELLING:
  SAVE_CACHE: True
