MODEL:
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
  PROPOSAL_GENERATOR:
    NAME: "CustomRPN"
  META_ARCHITECTURE: "CustomRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn2c4_backbone"
    FREEZE_AT: 0
  RESNETS:
    NORM: "SyncBN"
    STRIDE_IN_1X1: False
    DEPTH: 50
    OUT_FEATURES: [ "res2", "res3", "res4"]
  FPN:
    NORM: "SyncBN"
    IN_FEATURES: [ "res2", "res3", "res4"]
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "CustomRes5ROIHeadsExtraNorm"
  WEIGHTS: "models/res50_c4_soco_400.pkl"
  ROI_BOX_HEAD:
    RANDOM_DROPOUT: 0.5
    NORM_TEMP: 25.0
    USE_BIAS: -20.0
    CLS_AGNOSTIC_BBOX_REG: True
    USE_SIGMOID_CE: True
    USE_ZEROSHOT_CLS: True
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/coco_clip_attn12.npy'
    IGNORE_ZERO_CATS: True
    CAT_FREQ_PATH: 'datasets/coco/zero-shot/instances_train2017_seen_2_oriorder_cat_info.json'
    NUM_WORDS: 4
    WORD_EMBED_DIM: 512
    CLS_LOSS_WEIGHT: 1.0
  CLIP:
    NAME: 'ViT-B/32'
    USE_IMAGE_ENCODER: False
    MODEL_ROOT: 'models'

DATASETS:
  TRAIN: ("coco_zeroshot_train_oriorder",)
  TEST: ("coco_generalized_zeroshot_val",)
SOLVER:
  IMS_PER_BATCH: 16
  WEIGHT_DECAY: 0.000025
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 30000
INPUT:
  MIN_SIZE_TRAIN: (800,)
  FORMAT: "RGB"
VERSION: 2
OUTPUT_DIR: output/Detic-COCO/auto
FP16: True
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
TEST:
  PRECISE_BN:
    ENABLED: True