_BASE_: "../Base_OVCOCO_FPN_1x.yaml"
MODEL:
  ROI_BOX_HEAD:
    RANDOM_DROPOUT: 0.5
    NORM_TEMP: 25.0
    USE_BIAS: -20.0
  PROPOSAL_GENERATOR:
    NAME: "IOURPN"
  CLIP:
    USE_IMAGE_ENCODER: True
  WITH_IMAGE_LABELS: False

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False

SOLVER:
  CHECKPOINT_PERIOD: 10000