_BASE_: "./Base_OVCOCO_C4_1x_soco.yaml"
MODEL:
  PROPOSAL_GENERATOR:
    NAME: "RPN"
  META_ARCHITECTURE: "ProposalNetwork"
  RPN:
    PRE_NMS_TOPK_TEST: 2000  # Per FPN level
    POST_NMS_TOPK_TEST: 1000
  WEIGHTS: "models/res50_fpn_soco_star_400.pkl"

DATASETS:
  TRAIN: ("coco_zeroshot_train_oriorder",)
  TEST: ("coco_2017_train",)
SOLVER:
  IMS_PER_BATCH: 16
  WEIGHT_DECAY: 0.000025
  BASE_LR: 0.02
  STEPS: (100000, 133333)
  MAX_ITER: 150000
  CHECKPOINT_PERIOD: 50000