MODEL:
  WEIGHTS: "models/res50_fpn_soco_star_400.pkl"
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
  PROPOSAL_GENERATOR:
    NAME: "CustomRPN"
  META_ARCHITECTURE: "CustomRCNN"
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    STRIDE_IN_1X1: False
    DEPTH: 50
    NORM: "SyncBN"
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  FPN:
    NORM: "SyncBN"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "CustomStandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    RANDOM_DROPOUT: 0.5
    NORM_TEMP: 50.0
    USE_BIAS: 0.0
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "SyncBN"
    POOLER_RESOLUTION: 7
    CLS_AGNOSTIC_BBOX_REG: True
    USE_SIGMOID_CE: False
    USE_ZEROSHOT_CLS: True
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/coco_clip_attn12.npy'
    IGNORE_ZERO_CATS: True
    CAT_FREQ_PATH: 'datasets/coco/zero-shot/instances_train2017_seen_2_oriorder_cat_info.json'
    NUM_WORDS: 4
    WORD_EMBED_DIM: 512
    CLS_LOSS_WEIGHT: 1.0
  CLIP:
    NAME: 'ViT-B/32'
    USE_IMAGE_ENCODER: False
    MODEL_ROOT: 'models'
DATASETS:
  TRAIN: ("coco_zeroshot_train_oriorder",)
  TEST: ("coco_generalized_zeroshot_val",)
SOLVER:
  WEIGHT_DECAY: 0.000025
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 1000000
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
TEST:
  EVAL_PERIOD: 10000
  PRECISE_BN:
    ENABLED: True
OUTPUT_DIR: "./output/Detic-COCO/auto"