_BASE_: "./res50_fpn_soco_1x_clip_kd_detach_obj_mask_for_pos.yaml"
MODEL:
  META_ARCHITECTURE: "ProposalNetwork"
  PROPOSAL_GENERATOR:
    NAME: "RPN"
DATASETS:
  TEST: ("coco_zeroshot_val", "coco_not_zeroshot_val")