MODEL:
  META_ARCHITECTURE: "CustomProposalNetwork"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: [ "res2", "res3", "res4", "res5" ]
  FPN:
    IN_FEATURES: [ "res2", "res3", "res4", "res5" ]
  RPN:
    PRE_NMS_TOPK_TEST: 12000
    POST_NMS_TOPK_TEST: 1000
  WEIGHTS: "models/R-50.pkl"

DATASETS:
  TRAIN: ("coco_zeroshot_train_oriorder",)
  TEST: ("coco_sampled_train",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 10000
INPUT:
  MIN_SIZE_TRAIN: (800,)
VERSION: 2
OUTPUT_DIR: output/Detic-COCO/auto
FP16: True
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
