_BASE_: "../Base_OVCOCO_FPN_1x.yaml"
MODEL:
  ROI_HEADS:
    NAME: "CustomStandardROIHeadsV2"
  ROI_BOX_HEAD:
    RANDOM_DROPOUT: 0.5
    NORM_TEMP: 25.0
    USE_BIAS: -20.0
  PROPOSAL_GENERATOR:
    NAME: "CustomRPN"
  CLIP:
    USE_IMAGE_ENCODER: True
  WITH_IMAGE_LABELS: False
CONTEXT_MODELLING:
  PROPOSALS: "datasets/coco/zero-shot/instances_train2017_seen_2_proposal.json"
  ENABLE: True
  DETACH_BASE: False
  CONTRAST_LOSS_WEIGHT: 0.5
  TOKEN_LOSS_WEIGHT: 0.05
  TOPK: 300
  OBJECTNESS_THR: 0.0
  SHAPE_RATIO_THR: 0.1
  POSITIONAL_ENCODING: True
  CE_TEMP: 30.0
  TOKEN_TEMP: 50.0
  CHECKBOARD:
    ENABLE: True
    NMS_THR: 0.3
    AREA_RATIO_THR: 0.01
    BASE_PROBABILITY: 0.3
    MAX_GROUPS: 4
    MAX_PERMUTATIONS: 2
    ALPHA: 3.0
    INTERVAL: -0.20
    CUT_OFF_THR: 0.3
    LOCAL_CORRESPONDENCE: True
  CAPTION:
    ENABLE: False
  QUEUE:
    LENGTHS: [1024, 1024, 1024, 1024]
    NAMES: ['clip_text_features', 'clip_image_features', 'clip_word_features', 'clip_patch_features']

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
TEST:
  EVAL_PERIOD: 10000
SOLVER:
  CHECKPOINT_PERIOD: 10000