MODEL:
  META_ARCHITECTURE: "CustomDeformableDetr"
  WEIGHTS: "models/R-50.pkl"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res3", "res4", "res5"]
  DETR:
    CLS_WEIGHT: 2.0
    GIOU_WEIGHT: 2.0
    L1_WEIGHT: 5.0
    NUM_OBJECT_QUERIES: 300 # 300
    DIM_FEEDFORWARD: 1024
    WITH_BOX_REFINE: True
    TWO_STAGE: True
    NUM_CLASSES: 80
    USE_FED_LOSS: False
  ROI_BOX_HEAD:
    LEARN_BG: False
    RANDOM_DROPOUT: 0.5
    NORM_TEMP: 50.0
    USE_BIAS: 0.0
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/coco_clip_hand_craft_attn12.npy'
    IGNORE_ZERO_CATS: True
    CAT_FREQ_PATH: 'datasets/coco/zero-shot/instances_train2017_seen_2_oriorder_cat_info.json'
    NUM_WORDS: 6
    WORD_EMBED_DIM: 512
  CLIP:
    NAME: 'ViT-B/32'
    USE_IMAGE_ENCODER: False
    MODEL_ROOT: 'models'
DATASETS:
  TRAIN: ("coco_zeroshot_train_oriorder",)
  TEST: ("coco_generalized_zeroshot_val",)
SOLVER:
  CHECKPOINT_PERIOD: 10000000
  USE_CUSTOM_SOLVER: True
  IMS_PER_BATCH: 32     # 32 = 4x8 = 2 x 16
  BASE_LR: 0.0002      #  2xe-4
  STEPS: (300000,)
  MAX_ITER: 375000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  CUSTOM_MULTIPLIER: 0.1
  CUSTOM_MULTIPLIER_NAME: ['reference_points', 'sampling_offsets']
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  CUSTOM_AUG: "DETR"
TEST:
  DETECTIONS_PER_IMAGE: 100
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
OUTPUT_DIR: "output/Detic-detr/auto"
VERSION: 2
FP16: True