MODEL:
  PROPOSAL_GENERATOR:
    NAME: "CustomRPN"
  META_ARCHITECTURE: "CustomRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 6000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "CustomRes5ROIHeads"
  WEIGHTS: "models/R-50.pkl"
  RESNETS:
    DEPTH: 50
  ROI_BOX_HEAD:
    RANDOM_DROPOUT: 0.5
    NORM_TEMP: 25.0
    USE_BIAS: -20.0
    CLS_AGNOSTIC_BBOX_REG: True
    USE_SIGMOID_CE: True
    USE_ZEROSHOT_CLS: True
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/coco_clip_attn12.npy'
    IGNORE_ZERO_CATS: True
    CAT_FREQ_PATH: 'datasets/coco/zero-shot/instances_train2017_seen_2_oriorder_cat_info.json'
    NUM_WORDS: 4
    WORD_EMBED_DIM: 512
    CLS_LOSS_WEIGHT: 1.0
  CLIP:
    NAME: 'ViT-B/32'
    USE_IMAGE_ENCODER: False
    MODEL_ROOT: 'models'

DATASETS:
  TRAIN: ("coco_zeroshot_train_oriorder",)
  TEST:  ("coco_zeroshot_val", "coco_not_zeroshot_val")
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 10000
INPUT:
  MIN_SIZE_TRAIN: (800,)
VERSION: 2
OUTPUT_DIR: output/Detic-COCO/auto
FP16: True
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True