MODEL:
  PROPOSAL_GENERATOR:
    NAME: "CustomRPN"
  META_ARCHITECTURE: "CustomRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
    FREEZE_AT: 0
  RESNETS:
    NORM: "SyncBN"
    STRIDE_IN_1X1: True
    DEPTH: 50
    OUT_FEATURES: [ "res2", "res3", "res4", "res5" ]
  FPN:
    NORM: "SyncBN"
    IN_FEATURES: [ "res2", "res3", "res4", "res5" ]
  ANCHOR_GENERATOR:
    SIZES: [ [ 32 ], [ 64 ], [ 128 ], [ 256 ], [ 512 ] ]  # One size for each in feature map
    ASPECT_RATIOS: [ [ 0.5, 1.0, 2.0 ] ]  # Three aspect ratios (same for all in feature maps)
  RPN:
    CONV_DIMS: [-1, -1]
    IN_FEATURES: [ "p2", "p3", "p4", "p5", "p6" ]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "CustomStandardROIHeads"
    IN_FEATURES: [ "p2", "p3", "p4", "p5" ]
  ROI_BOX_HEAD:
    RANDOM_DROPOUT: 0.5
    NORM_TEMP: 25.0
    USE_BIAS: -20.0
    NAME: "FastRCNNConvFCHead"
    POOLER_RESOLUTION: 7
    NUM_CONV: 4
    NORM: "SyncBN"
    NUM_FC: 1
    CLS_AGNOSTIC_BBOX_REG: True
    USE_SIGMOID_CE: True
    USE_ZEROSHOT_CLS: True
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/coco_clip_attn12.npy'
    IGNORE_ZERO_CATS: True
    CAT_FREQ_PATH: 'datasets/coco/zero-shot/instances_train2017_seen_2_oriorder_cat_info.json'
    NUM_WORDS: 4
    WORD_EMBED_DIM: 512
    CLS_LOSS_WEIGHT: 1.0
  CLIP:
    NAME: 'ViT-B/32'
    USE_IMAGE_ENCODER: False
    MODEL_ROOT: 'models'

DATASETS:
  TRAIN: ("coco_zeroshot_train_oriorder",)
  TEST: ("coco_generalized_zeroshot_val",)
SOLVER:
  CLIP_GRADIENTS:
    ENABLED: True
  AMP:
    ENABLED: True
  IMS_PER_BATCH: 32
  WEIGHT_DECAY: 0.00004
  WARMUP_FACTOR: 0.067
  WARMUP_ITERS: 500
  BASE_LR: 0.1
  STEPS: (320000, 340000)
  MAX_ITER: 360000
  CHECKPOINT_PERIOD: 60000
INPUT:
  CUSTOM_AUG: 'LargeScaleJittering'
  SCALE_RANGE: [0.1, 2.0]
  TRAIN_SIZE: 1024

VERSION: 2
OUTPUT_DIR: output/Detic-COCO/auto
FP16: True
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
TEST:
  EVAL_PERIOD: 10000