MODEL:
  PIXEL_MEAN: [ 123.675, 116.280, 103.530 ]
  PIXEL_STD: [ 58.395, 57.120, 57.375 ]
  WEIGHTS: "models/res50_fpn_soco_star_400.pkl"
  MASK_ON: True
  META_ARCHITECTURE: "CustomRCNN"
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    NORM: "SyncBN"
    OUT_FEATURES: [ "res2", "res3", "res4", "res5" ]
  FPN:
    NORM: "SyncBN"
    IN_FEATURES: [ "res2", "res3", "res4", "res5" ]
  ANCHOR_GENERATOR:
    SIZES: [ [ 32 ], [ 64 ], [ 128 ], [ 256 ], [ 512 ] ]  # One size for each in feature map
    ASPECT_RATIOS: [ [ 0.5, 1.0, 2.0 ] ]  # Three aspect ratios (same for all in feature maps)
  PROPOSAL_GENERATOR:
    NAME: "CustomRPN"
  RPN:
    IN_FEATURES: [ "p2", "p3", "p4", "p5", "p6" ]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: 'FPNSumStandardROIHeads'
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    NUM_CLASSES: 1203
    SCORE_THRESH_TEST: 0.0001
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_CONV: 4
    NUM_FC: 1
    NORM: "SyncBN"
    POOLER_RESOLUTION: 7
    RANDOM_DROPOUT: 0.5
    NORM_TEMP: 50.0
    USE_BIAS: 0.0
    CLS_AGNOSTIC_BBOX_REG: True
    USE_ZEROSHOT_CLS: True
    USE_SIGMOID_CE: False
    USE_FED_LOSS: False
    IGNORE_ZERO_CATS: False              # do not ignore zero cats
    ZEROSHOT_WEIGHT_PATH: 'datasets/metadata/lvis_v1_clip_att12.npy'
    CAT_FREQ_PATH: 'datasets/metadata/lvis_v1_train_cat_info.json'
    NUM_WORDS: 4
    WORD_EMBED_DIM: 512
    CLS_LOSS_WEIGHT: 1.0
  CLIP:
    NAME: 'ViT-B/32'
    USE_IMAGE_ENCODER: False
    MODEL_ROOT: 'models'
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    NORM: "SyncBN"
    POOLER_RESOLUTION: 14
    CLS_AGNOSTIC_MASK: True

DATASETS:
  TRAIN: ("lvis_v1_train_norare",)
  TEST: ("lvis_v1_val",)
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
TEST:
  DETECTIONS_PER_IMAGE: 300  # LVIS allows up to 300
  PRECISE_BN:
    ENABLED: True
SOLVER:
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WEIGHT_DECAY: 0.000025
  CHECKPOINT_PERIOD: 30000
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  WARMUP_FACTOR: 0.0002
  WARMUP_ITERS: 5000
  CLIP_GRADIENTS:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  FORMAT: "RGB"
OUTPUT_DIR: "./output/Detic/auto"
EVAL_PROPOSAL_AR: False
VERSION: 2
FP16: True